---
# This is an Ansible playbook.
# Run it with: ansible-playbook -K <THIS-FILE>
# Last updated for Fedora 31.
- hosts: localhost
  vars:
    home: "{{ ansible_env.HOME }}"
  tasks:
    - name: Upgrade all packages
      become: true
      tags: [sudo]
      dnf:
        name: "*"
        state: latest
    - name: Setup hostname
      vars:
        desired_hostname: zal
        hostname_path: /etc/hostname
      when: ansible_env.HOSTNAME != desired_hostname
      block:
        - hostname:
            name: "{{desired_hostname}}"
          become: true
          tags: [sudo]
        - shell: "echo {{desired_hostname}} >{{hostname_path}}"
          when: lookup('file', hostname_path) != desired_hostname
          become: true
          tags: [sudo]
    - name: Install basic tooling
      become: true
      tags: [sudo]
      package:
        state: present
        name:
          - asciinema
          - bat
          - chrome-gnome-shell
          - colordiff
          - dnf-plugins-core
          - exa
          - fd-find
          - fish
          - flameshot
          - fzf
          - gnome-tweaks
          - google-roboto-fonts
          - gparted
          - graphviz
          - htop
          - hub
          - jq
          - levien-inconsolata-fonts
          - linux-libertine-fonts
          - most
          - neovim
          - python3-neovim
          - ripgrep
          - ruby-devel
          - tmux
          - tokei
          - units
          - xclip
          - yamllint
    - name: Neovim Plugins
      tags: [vim]
      vars:
        site: "{{ home }}/.local/share/nvim/site"
      block:
        - file:
            path: "{{ site }}"
            state: directory
        - git:
            repo: git@github.com:thilp/nvim-plugins.git 
            dest: "{{ site }}/pack"
            track_submodules: true
    - name: Alacritty
      become: true
      tags: [sudo, alacritty]
      block:
        - command:
            cmd: "dnf copr enable pschyska/alacritty"
            stdin: "y"
            warn: false
            creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:pschyska:alacritty.repo
        - package:
            state: present
            name: alacritty
    - name: Python
      tags:
        - python
      block:
        - name: Install Python
          become: true
          tags: [sudo]
          package:
            state: present
            name:
              - python3
              - autoconf
              - bzip2
              - bzip2-devel
              - libffi-devel
              - libtool
              - lldb
              - python-lldb
              - python-devel
              - python3-devel
              - python3-pip
              - readline
              - readline-devel
              - sqlite-devel
              - zlib-devel
        - name: Install Pyenv
          git:
            repo: https://github.com/pyenv/pyenv.git
            dest: "{{home}}/.pyenv"
        - name: Install Pipenv
          pip:
            name: pipenv
            extra_args: --user --upgrade
        - name: Poetry
          tags:
            - poetry
          vars:
            installer: /tmp/get-poetry.py
          block:
            - name: Download the Poetry installer
              when: installer is not exists
              get_url:
                url: https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
                dest: "{{installer}}"
            - name: Run the Poetry installer
              command: "python3 {{installer}}"
              register: poetry_install
              changed_when: "'already installed' not in poetry_install.stdout"
    - name: Install Java
      become: true
      tags: [sudo]
      package:
        state: present
        name:
          - java-latest-openjdk-headless
          - java-latest-openjdk-devel
          - java-latest-openjdk-src
          - java-latest-openjdk-javadoc
    - name: VSCode
      block:
        - name: Install the VSCode repository
          become: true
          tags: [sudo]
          yum_repository:
            name: vscode
            description: Visual Studio Code
            baseurl: https://packages.microsoft.com/yumrepos/vscode
            enabled: true
            gpgcheck: true
            gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        - name: Install VSCode
          become: true
          tags: [sudo]
          package:
            state: present
            name: code
    - name: Docker
      tags:
        - docker
      block:
        - name: Ask whether Docker is already installed
          command: which docker
          register: which_docker
          changed_when: false
          failed_when: false
        - when: which_docker.rc != 0
          block:
            - name: Download & install Docker
              become: true
              tags: [sudo]
              shell: curl -fsSL get.docker.com | CHANNEL=test sh
            - name: Add me in the docker group
              become: true
              tags: [sudo]
              user:
                name: "{{ lookup('env', 'USER') }}"
                groups: [docker]
                append: true
            - name: Enable & start Docker with systemd
              become: true
              tags: [sudo]
              systemd:
                name: docker
                state: started
                enabled: true
    - name: Jetbrains IDEs
      tags:
        - jetbrains
      block:
        - name: Increase inotify watch limit
          become: true
          tags: [sudo]
          sysctl:
            name: fs.inotify.max_user_watches
            value: "524288"
            sysctl_file: /etc/sysctl.d/jetbrains.conf
            reload: true
        - vars:
            tb_exe: "{{home}}/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox"
            archive_path: /tmp/jetbrains_toolbox.tar.gz
          when: tb_exe is not exists
          block:
            - name: Download Jetbrains Toolbox
              vars:
                tb_json: "{{ lookup('url', 'https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release') | from_json }}"
                tb_url: "{{ tb_json | json_query('TBA[0].downloads.linux.link') }}"
                # tb_checksum_url: "{{ tb_json | json_query('TBA[0].downloads.linux.checksumLink') }}"
              get_url:
                url: "{{ tb_url }}"
                # checksum: "sha256:{{ tb_checksum_url }}"
                dest: "{{ archive_path }}"
            - name: Create temporary directory
              tempfile:
                state: directory
                suffix: jetbrains
              register: extracted_path
            - name: Install Jetbrains Toolbox
              unarchive:
                remote_src: true
                src: "{{ archive_path }}"
                dest: "{{ extracted_path }}"
            - name: Locate the Jetbrains Toolbox executable
              find:
                paths: "{{ extracted_path }}"
                patterns: jetbrains-toolbox
                recurse: true
              register: find_toolbox
            - name: Execute the Jetbrains Toolbox executable for the user
              command: "{{ find_toolbox.files[0].path }} "
            - debug:
                msg: The toolbox should be open. If not, try opening it
                      manually at {{ find_toolbox.files[0].path }}.
                      Waiting until {{ tb_exe }} has been created ...
            - wait_for:
                path: "{{ tb_exe }}"
                msg: Timeout while waiting for {{ tb_exe }}. Please install manually.
    - name: Golang
      tags:
        - go
        - golang
        - languages
      vars:
        version: 1.13.4
        goroot: "{{home}}/.golang"
        dl_url: "https://dl.google.com/go/go{{version}}.linux-amd64.tar.gz"
        tmp_archive: /tmp/golang.tar.gz
        tmp_dir: /tmp/golang
      when: ( goroot is not exists ) or
              ( lookup('file', goroot ~ "/VERSION") != "go" ~ version )
      block:
        - name: Download the latest Golang archive
          when: tmp_archive is not exists
          get_url:
            url: "{{dl_url}}"
            dest: "{{tmp_archive}}"
            checksum: "sha256:{{ lookup('url', dl_url ~ '.sha256') }}"
        - name: Create temporary directory for extraction of the Golang archive
          tempfile:
            state: directory
            suffix: golang
          register: tmp_dir
        - name: Extract the latest Golang archive into the temporary directory
          unarchive:
            remote_src: true
            src: "{{tmp_archive}}"
            dest: "{{ tmp_dir.path }}"
        - name: Remove the existing $GOROOT
          file:
            path: "{{goroot}}"
            state: absent
        - name: Populate $GOROOT
          command: "mv {{ tmp_dir.path }}/go {{goroot}}"
    - name: staticcheck
      tags:
        - go
        - golang
        - linter
      command:
        cmd: go get honnef.co/go/tools/cmd/staticcheck
        creates: "{{ home }}/go/bin/staticcheck"

    - name: Vivaldi
      become: true
      tags: [sudo]
      block:
        - name: Install the Vivaldi repository
          yum_repository:
            name: vivaldi
            description: The Vivaldi Web Browser
            enabled: true
            baseurl: https://repo.vivaldi.com/archive/rpm/$basearch
            gpgcheck: true
            gpgkey: https://repo.vivaldi.com/archive/linux_signing_key.pub
        - name: Install the Vivaldi package
          package:
            name: vivaldi-stable
            state: present

    - name: char command
      vars:
        repo: "{{home}}/git/unicli"
        fish_func_dir: "{{home}}/.config/fish/functions"
        func_file: char.fish
      when: repo is exists
      block:
        - name: Create ~/.unicode.data
          command: fish make.fish
          args:
            chdir: "{{repo}}"
            creates: "{{home}}/.unicode.data"
        - name: Install the char function in Fish
          command: "cp {{func_file}} {{fish_func_dir}}"
          args:
            chdir: "{{repo}}"
            creates: "{{fish_func_dir}}/{{func_file}}"

    - name: Clojure
      tags:
        - clojure
        - languages
      vars:
        path: "{{ home }}/bin/lein"
      block:
        - file:
            path: "{{ home }}/bin"
            state: directory
        - name: Leiningen
          get_url:
            url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
            dest: "{{ path }}"
            mode: a+x

    - name: git diff
      tags: [git]
      get_url:
        url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
        dest: "{{ home }}/bin/diff-so-fancy"
        mode: a+rx
